### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Anton-Interon** [LoganPeck/Umbraco-Archetype-Model-Binder-Add-On#1]
Good Day

Please can you provide me wit installation instructions for the Add-On

Thanks In advance

**Comment by LoganPeck** [comment]
Hello Anton, I just updated the repo with the latest source code. The only things you SHOULD need to get this setup is to download the source and compile it into your project. Then add these two settings to your web.config appSettings section.

<add key="CustomModelBuilderNamespace" value="Website.Models.Generated" />
<add key="CustomModelBuilderAssembly" value="Website" />

The first one is the namespace you want your models to be generated under.
The second is the name of the assembly that the models are generated in (This will be the name of the dll your project gets compiled into)
The only other thing I can think of is that you will need to make sure the folder /Models/Generated exists.

Let me know how it goes.

**Comment by Anton-Interon** [comment]
Thanks for your help.

Now I get a

//We need to return a list of the type
Line 86:                 Type listType = typeof(IEnumerable<>);
Line 87:                 Type archetypeTypeList = listType.MakeGenericType(archetypeType);
Line 88:
Line 89:                 return archetypeTypeList;

Source File: c:\inetpub\wwwroot\uGamco\App_Code\PropertyValueConverters\Helpers\ArchetypeValueProvider.cs    Line: 87

Stack Trace:

[ArgumentNullException: Value cannot be null.]

**Comment by LoganPeck** [comment]
Ok, looks like you are close. So it looks like you are dealing with nested archetypes possibly? One little snag that I always run into here is with nested archetypes. You must first save the archetype that is nested, and then make sure you find the source file that the models builder generated (/Models/Generated) and include it in your visual studio project. The problem that it is having is its trying to make an IEnumerable of whatever your archetype type is. However, it can’t find that type in your project. So once again, make sure you save your nested archetype first, then include it in your project, then clean and rebuild your solution.

I wish there was a better way to handle this case but this was the best solution I could come up with.

Feel free to keep reaching out to me, this makes it so nice to work with Archetype and the Zbu models builder.

**Comment by Anton-Interon** [comment]
Ok. When I try to save any archetype I get the following 

Received an error from the server
Failed to save data for data type id 1930

The table name is not valid. [ Token line number (if known) = 1,Token line offset (if known) = 23,Table name = cmsDataTypePreValues ]

EXCEPTION DETAILS:

System.Data.SqlServerCe.SqlCeException: The table name is not valid. [ Token line number (if known) = 1,Token line offset (if known) = 23,Table name = cmsDataTypePreValues ]
STACKTRACE:

at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeCommand.CompileQueryPlan()
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs:line 248
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at Umbraco.Core.Persistence.Database.<Query>d__7`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Core.Persistence.Database.Fetch[T](String sql, Object[] args)

**Comment by LoganPeck** [comment]
Ok, that is coming from a bug that was in the version of umbraco that I was running. If you look at line 44 in the /App_start/ModelBinderEvents.cs that is where it is coming from. I would be willing to bet that you are running a different version of umbraco than I developed this for (7.2.6). You could modify this line of code to pull from whatever the table name is for the cmsDataTypePreValues table in your database.

Sorry for all of the trouble, this hasn’t been thourougly tested on all enviornments.

**Comment by LoganPeck** [comment]
Another thing you could try is commening out line 44 in App_Start/ModelBinderEvents.cs and uncommenting line 47

**Comment by Anton-Interon** [comment]
commening out line 44 in App_Start/ModelBinderEvents.cs and uncommenting line 47

Worked Thanks

**Comment by LoganPeck** [comment]
Yup, no problem, one thing I noticed when uncommenting out line 47 is that you have to save the archetype twice for the changes to be built into your new model. This was a bug in the version of umbraco I was running with the data type service. I don’t know if you will run into that issue or not. If you run into anything else please let me know. I have built a few sites with this now with no problems. Good luck!

**Comment by Anton-Interon** [comment]
Regarding the NullExeption Error.

I don't have a nested archetype I have a Grid Layout as one of the fields 

  //We need to return a list of the type
Line 86:                 Type listType = typeof(IEnumerable<>);
Line 87:                 Type archetypeTypeList = listType.MakeGenericType(archetypeType);
Line 88: 
Line 89:                 return archetypeTypeList;

Source File: c:\inetpub\wwwroot\uGamco\App_Code\PropertyValueConverters\Helpers\ArchetypeValueProvider.cs    Line: 87 
[ArgumentNullException: Value cannot be null.]

Please Advise

**Comment by LoganPeck** [comment]
Sorry, I just saw this. Anytime you see this error it is because the type of one of your archetype properties cannot be found.

For example, if you add a property to your archetype of type Grid, the archetype model binder will generate the property with the type Newtonsoft.Json.Linq.JToken.
So you could get this null reference exception if the archetype builder cannot find Newtonsoft.Json.Linq.JToken.

What is interesting to me is that it is trying to make a list of something. What data types are you using on the archetype you are trying to save?

Also, just as a double check, did you rebuild your solution after updating the archetype in the backoffice? This is necessary to make sure that the latest model cs file is included in your dll.

Thanks for being patient in trying to work out all of the bugs.

**Comment by Anton-Interon** [comment]
Hi 

This is the generated model

/*
This is auto generated code
*/
using System;
using Archetype;

namespace MyAModels
{

```
public partial class Menu
{
    public System.String Name {get; set;}

    public Newtonsoft.Json.Linq.JToken Content {get; set;}

    public Newtonsoft.Json.Linq.JToken Link {get; set;}

}
```

}

**Comment by Anton-Interon** [comment]
Please excuse my ignorance here but where do I find the AssemblyName to put into CustomModelBuilderAssembly

I'm running umbraco on iis

**Comment by LoganPeck** [comment]
No worries, it is normally your project name. If you look in your bin folder, you should see a dll with your projects name unless you configured it differently.

**Comment by LoganPeck** [comment]
That looks great. Now, you need to make sure you add that file to your solution, and then rebuild your solution. Then when you go to render your page that uses that model, it should work fine.
Let me know if that doesn’t work. Just double checking, your namespace in the appsettings in your web.config is “MyAModels” correct?

**Comment by Anton-Interon** [comment]
Yes it is. And Yes it has compiled.

**Comment by LoganPeck** [comment]
Awesome, let me know if you have any other issues with it or suggestions.

**Comment by Anton-Interon** [comment]
Good I'm on the right track but still have the same error

**Comment by Anton-Interon** [comment]
Ok I managed to resolve the problem.

Because I’m running umbraco on IIS the your code gets compiled at runtime thus no assembly (Please correct me if I’m wrong)

GetType (“Namespace.ClassName”) fixed the problem

  public static Type GetArchetypeType(ArchetypePrevalueChecker ruleChecker, ArchetypePreValue archPrevalue, string dataTypeName)
        {
            Type archetypeType;

```
        if (ruleChecker.HasMultipleFieldsets()) //Multiple fieldsets are enabled so we need to set the type to an interface
        {
            string interfaceName = ArchetypeValueProvider.StringToInterfaceName(dataTypeName);

            archetypeType = Type.GetType(GetModelsNamespace() + "." + interfaceName + ", " + GetAssemblyName());
        }
        else //No multiple fieldsets so just a class as the type
        {
            ArchetypePreValueFieldset fieldset = archPrevalue.Fieldsets.First();
            MyAModels.Menu m = new MyAModels.Menu();
            string className = fieldset.Alias.ToFirstUpperInvariant();
            var a = System.Reflection.Assembly.GetCallingAssembly().FullName;
            //string className = propertyType.PropertyTypeAlias.UppercaseFirstLetter();
          //  archetypeType = Type.GetType(GetModelsNamespace() + "." + className + ", " + GetAssemblyName());
            archetypeType = Type.GetType(GetModelsNamespace() + "." + className ); << Fix
        }
        return archetypeType;
    }
```
